### ISSUE TITLE
Make Phone number not click dialable in mobile

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/land_acknowledgement#22]
Since we don't have a voice option, we want to discourage people from voice calling the phone number, it also incurs charges. Can we make it so on iPhones it doesn't have a URL click to call option?

**Comment by mark-meyer** [comment]
I pushed a very small commit to master that adds:

`<meta name="format-detection" content="telephone=no">`

This works to prevent the link on my iPhone. I'm not sure if it's universal.

**Comment by TechSolomon** [comment]
This issue is fixed in 81f77d54e13c49a70d8d7b9acc0d79c696cd455d.
